### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by sastoudt** [arives/rr2#11]
For JOSS review: https://github.com/openjournals/joss-reviews/issues/1028

- [x] testthat.R results in Error: No tests found for rr2 

I ran the tests manually, and they passed. However, for the commented out tests I was not able to test them manually because phyr is not available for R version 3.5.1, 3.3.3, 3.2.5, or 3.1.3. 

- [x] include expect_message tests regarding lack of particular methods for communityPGLM

**Comment by daijiang** [comment]
Hi @sastoudt 
Thanks for your help with the package! I think the Error is because you tried to run `test that.R`.  If you use `devtools::test(pkg = ".")` to test the package, you should get no error.

We commented out the test about `phyr` because this package is still under development and is not stable yet. We added expect message about communityPGLMM. We will uncomment these sections when `phyr` is stable.
