### ISSUE TITLE
potential bug in r2_lik.R?

### ISSUE THREAD

**Issue by atanzap** [arives/rr2#13]
Thanks Tony for the great package!

I noticed some funny behaviour with rr2_1.0.2 and a phyloglm that I wanted to run past you.  

The R2.lik.phyloglm function in [r2_lik.R](https://github.com/arives/rr2/blob/master/R/r2_lik.R#L303) takes the model log-likelihood.  But depending on the model fit, this can actually lead to negative values of R2_lik, which seems to contradict your 2019 Syst Biol [paper](https://academic.oup.com/sysbio/article/68/2/234/5098616).  

According to the paper, shouldn't you be taking the penalized ML?  So ` LL.r <- mod.r$logLik` should be replaced with ` LL.r <- mod.r$penlogLik` in the R2.lik.phyloglm function?

Cheers
Andrew

**Comment by arives** [comment]
Andrew,

Thanks for the question. I think what might be going on is that the phylogenetic parameter in phyloglm is estimated as showing no signal (e.g., alpha=50). In this case, all the results you get for parameters (other than alpha) and the logLik are suspect, because phyloglm is bad at finding ML estimates at parameter boundaries. When the phylogenetic signal is estimated by phyloglm as zero, I automatically use lm or glm.

Try this, and I bet the problem goes away. Even though phyloglm can use the penalized LL for solutions, the unpenalized ML should be generally be used for LRTs and r2_lik.

Let me know what happens! And thanks for contacting me about this.

Cheers, Tony

**Comment by atanzap** [comment]
phyloglm estimates alpha=0.1089099, so that means this isn't the problem?...

**Comment by arives** [comment]
You’re right. But I’m still suspicious about the fitting.

Would you mind sending a file with the data and R script with the analyses so I can take a look? I’m in Iceland doing fieldwork right now, so I can’t guarantee I will look at it immediately. But I’ll try to get back to you quickly.

**Comment by atanzap** [comment]
Sorry for deleting the message.  Thought I made a mistake, but didn't.  Problem also happens with slightly larger alpha = 0.5.  

Yes - will email you now.  Thanks for looking at this!

**Comment by rvosa** [comment]
Hi! We are noticing what might be similar behavior but we are not quite sure. Using a phylolm we attempted to assess phylogenetic signal using Pagel's lambda (if that's even appropriate at all) and had a value of ±0.8, i.e. pretty high signal. Nevertheless, we get negative values for R2.lik.

Here we have a tiny gist that reproduces the behavior: https://gist.github.com/yuxin0406/cb9a80b21d86052ce4af21265c9c79e9

What are we looking at? We're not quite sure?
