### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by sastoudt** [arives/rr2#9]
For JOSS review: https://github.com/openjournals/joss-reviews/issues/1028

- [x] In the JOSS paper you mention that this package can be used to "compare contributions of predictor variables and/or correlation structure". It would be nice to have an example of this in the README.md
- [x] add example usage of partialR2() and partialR2adj() to README.md
- [ ] add example usage of communityPGLMM() to README.md
- [x] note change in binaryPGLMM() from the ape package in README.md
- [x]  add example usage of different values for parameter sigma2_d in README.md

**Comment by daijiang** [comment]
@sastoudt Thanks! We have added more examples in README.md. However, we did not add example for `phyr::commuintyPGLMM()` because it is not stable yet. At this stage, we don't want to put `phyr` as a package imported or suggested by `rr2`, which will be required if we add examples about it in README (and add tests). We have tested the usage of `rr2::R2()` on `phyr::commuintyPGLMM()` locally. When `phyr` is stable in the near future, we will add examples in the README.md and tests in the test folder.
